spring:
  application:
    name: spring-batch
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:cdpdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Spring Batch Configuration
  batch:
    job:
      enabled: false  # Disable auto-start, we'll use scheduled orchestrator
    jdbc:
      initialize-schema: always
  
  # Enable task scheduling
  task:
    scheduling:
      enabled: true

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.claude.springbatch: DEBUG
    org.springframework.batch: INFO